---
components:
  securitySchemes:
    token:
      type: apiKey
      name: Authorization
      in: header
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/auth/login":
    post:
      summary: User token
      tags:
      - User
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  username:
                    type: string
                  user_id:
                    type: integer
                required:
                - username
      requestBody:
        content:
          application/json:
            schema:
              type: object
  "/stadiums":
    get:
      summary: list staduims
      tags:
      - Stadium
      security:
      - token: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  country:
                    type: string
                  seats:
                    type: integer
                  photo:
                    Type: string
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: www.ruta-deploy.com
