---
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/stadiums":
    get:
      summary: list staduims
      tags:
      - Stadiums
      responses:
        '200':
          description: successful
    post:
      summary: create stadium
      tags:
      - Stadiums
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                country:
                  type: string
                seats:
                  type: integer
                photo:
                  Type: string
              required:
              - name
              - country
              - seats
              - photo
  "/stadiums/{id}":
    get:
      summary: Show stadium
      tags:
      - Stadiums
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      security:
      - api_key: []
      responses:
        '200':
          description: stadium found
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  country:
                    type: string
                  seats:
                    type: integer
                  photo:
                    Type: string
                required:
                - name
                - country
                - seats
                - photo
        '404':
          description: blog not found
    delete:
      summary: delete stadium
      tags:
      - Stadiums
      responses:
        '200':
          description: successful
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: www.ruta-deploy.com
